[package]
name = "uk-traffic-accident-parser-cli"
version = "0.2.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "postgres", "macros", "uuid", "time"] }
clap = { version = "4.6.4", features = ["derive"] }
csv = "1.4.0"
serde = "1.0.229"
time = { version = "0.3.54", features = ["parsing", "formatting"] }
num-format = "0.4.4"
